export const SCENES = [
  "stole a cake",
  "grabbed money",
  "moved an object",
  "hid a remote control",
  "switched drinks",
  "took a cookie",
  "borrowed a pen",
  "relocated keys",
  "swiped a phone",
  "changed a setting",
  "adjusted thermostat",
  "flipped a switch",
  "closed a door",
  "opened a window",
  "rearranged books",
  "tilted a picture frame",
  "unplugged something",
  "stole food from fridge",
  "moved a chair",
  "hid shoes",
  "switched labels",
  "relocated glasses",
  "took batteries",
  "moved a plant",
  "hid the TV remote",
  "switched phone cases",
  "relocated wallet",
  "moved laptop",
  "took headphones",
  "hid a charger",
  "switched mugs",
  "moved mouse",
  "took notebook",
  "hid backpack",
  "relocated umbrella",
  "moved pillow",
  "took blanket",
  "hid magazine",
  "switched books",
  "moved vase",
  "took decoration",
  "hid toy",
  "switched cushions",
  "moved lamp",
  "took snack",
  "hid tablet",
  "switched plates",
  "moved utensils",
  "took leftovers",
  "hid spices",
  "switched containers",
  "moved cutting board",
  "took kitchen towel",
  "hid oven mitt",
  "switched bottles",
  "moved trash can",
  "took cleaning supplies",
  "hid sponge",
  "switched soaps",
  "moved toilet paper",
  "took towel",
  "hid toothbrush",
  "switched shampoo",
  "moved bath mat",
  "took cosmetics",
  "hid razor",
  "switched mirrors",
  "moved clothes",
  "took jewelry",
  "hid accessories",
  "switched hangers",
  "moved luggage",
  "took documents",
  "hid mail",
  "switched folders",
  "moved stapler",
  "took supplies",
  "hid scissors",
  "switched tape",
  "moved calendar",
  "took post-its",
]

export function getRandomScene(maxIndex: number = SCENES.length): string {
  const availableScenes = SCENES.slice(0, maxIndex)
  return availableScenes[Math.floor(Math.random() * availableScenes.length)]
}
